### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by cheliu-computation** [minghu0830/OphNet-benchmark#1]
Dear Authors,

May I ask when would the dataset released?
I have filled the form but have no response yet.

Best Regards

**Comment by minghu0830** [comment]
@cheliu-computation Hi, thank you for your interest in OphNet! We have successfully received your application. We are currently developing OphNet V2, which will feature more accurate and diverse labels, as well as a larger volume of videos for the upcoming challenge. Unfortunately, to prevent data leaks, we have to delay the data release plan. We have recorded your information and will contact you soon.

**Comment by minghu0830** [comment]
@cheliu-computation Thank you for your interest in OphNet. The dataset is now open-sourced; please refer to Dataset Preparation. If you have any other questions, feel free to leave a message.
