### ISSUE TITLE
When Can I Get the Dataset?

### ISSUE THREAD

**Issue by ErinWang2023** [minghu0830/OphNet-benchmark#2]
Dear authors, thank you for your sharing. I have submitted the licensing agreement. When will you send me the complete dataset?

**Comment by minghu0830** [comment]
Hi@ErinWang2023 , thank you for your interest in OphNet! We have successfully received your application. We are currently developing OphNet V2, which will feature more accurate and diverse labels, a larger volume of videos for the upcoming challenge, and will provide more baseline results. Unfortunately, to prevent data leaks, we have to delay the data release plan. We have recorded your information and will contact you once the final data preparation is completed. Please stay tuned to OphNet and the upcoming challenge.

**Comment by minghu0830** [comment]
@ErinWang2023 Thank you for your interest in OphNet. The dataset is now open-sourced; please refer to Dataset Preparation. If you have any other questions, feel free to leave a message.

**Comment by ErinWang2023** [comment]
谢谢你哦！！

**Comment by ErinWang2023** [comment]
Could you give me the Baidu Netdisk link, please?  I can't download from the huggingface, it always stop.

**Comment by minghu0830** [comment]
@ErinWang2023 Hi, I’ve updated the BaiduNetdisk download link. Additionally, HF-Mirror is a great alternative.

**Comment by ErinWang2023** [comment]
谢谢你哦！！
