### ISSUE TITLE
 Dataset request

### ISSUE THREAD

**Issue by Themistanny** [minghu0830/OphNet-benchmark#3]
Hello, thank you for your sharing. May I inquire when the new dataset will be made publicly available?

**Comment by minghu0830** [comment]
@Themistanny Thank you for your interest in OphNet! To track each download, we will be sending the data download link via email (we expect this to be completed within about a month). Please make sure that you have successfully filled out and submitted the data application form.

**Comment by minghu0830** [comment]
@Themistanny Thank you for your interest in OphNet. The dataset is now open-sourced; please refer to Dataset Preparation. If you have any other questions, feel free to leave a message.
