### ISSUE TITLE
Request for data

### ISSUE THREAD

**Issue by FXLYZ** [minghu0830/OphNet-benchmark#4]
Hi, it is an insightful work! And I want to follow it.
I have submitted the request form. But I haven't received download link.
Could you provide the download link?

**Comment by minghu0830** [comment]
@FXLYZ  Thank you for your attention. The new annotation work has exceeded our expectations, but we plan to complete it within three weeks. Please pay attention to the email response.

**Comment by 502463708** [comment]
Is anything going well with the new annotation work? Could you please kindly let me know when we can access the data? Thank you so much~

**Comment by minghu0830** [comment]
@FXLYZ @502463708 Thank you for your interest in OphNet. The dataset is now open-sourced; please refer to Dataset Preparation. If you have any other questions, feel free to leave a message.
