### ISSUE TITLE
Missing data_processing/cliper.py Script in Repository

### ISSUE THREAD

**Issue by GeorgezZzzzzZ** [minghu0830/OphNet-benchmark#6]
Hello,

Thank you for providing this repository and the resources for handling the OphNet2024 data. I noticed that the instructions mention using the script data_processing/cliper.py to trim videos based on annotated time boundaries. However, I couldn't locate this file in the repository.

Could you please provide the cliper.py script or guide us on how to proceed without it?

Thank you!

**Comment by FXLYZ** [comment]
Hi, I have the same issue!

**Comment by minghu0830** [comment]
@GeorgezZzzzzZ @FXLYZ Hello, I have uploaded the script, and over the next few days, I will be gradually uploading operation and phase-level trimmed videos to the HuggingFace repository for direct download, to help reduce data preprocessing time for everyone. If you have any other questions, please feel free to leave a message.
