### ISSUE TITLE
tar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by 123catfei** [minghu0830/OphNet-benchmark#7]
When I try to extract the video file, I get the following error:
`tar: Error opening archive: Unrecognized archive format`
How can I solve this problem?
Please!

**Comment by minghu0830** [comment]
@123catfei Can you tell me which archive it is? Is it OphNet2024_all, OphNet2024_trimmed_operation, or OphNet2024_trimmed_phase?

**Comment by minghu0830** [comment]
@123catfei The OphNet2024_trimmed_phase and OphNet2024_trimmed_operation archives appear to be corrupted. We will fix them as soon as possible. In the meantime, you can use cliper.py to trim the original videos.

**Comment by 123catfei** [comment]
> @123catfei The OphNet2024_trimmed_phase and OphNet2024_trimmed_operation archives appear to be corrupted. We will fix them as soon as possible. In the meantime, you can use cliper.py to trim the original videos.

Thank you very much for your reply, we are trying to download and unzip the untrimmed video!

**Comment by minghu0830** [comment]
@123catfei Hi, after comparing the MD5 checksums of the original and open-source compressed packages, we found that these three packages might be corrupted. We have re-uploaded and replaced them. You can download them individually, overwrite the old files, and try extracting them again. (Additionally, for the OphNet2024_trimmed_operation package, I have standardized **the prefix from OphNet to OphNet2024**. You can also rename the files you have already downloaded if needed): **OphNet2024_trimmed_operation/OphNet2024_trimmed_operation.tar.gz.01**, **OphNet2024_trimmed_phase/OphNet2024_trimmed_phase.tar.gz.02**, and **OphNet2024_trimmed_phase/OphNet2024_trimmed_phase.tar.gz.06**.
